### ISSUE TITLE
Can't install within Cloud Build

### ISSUE THREAD

**Issue by MarkEdmondson1234** [GoogleCloudPlatform/composer-local-dev#9]
I'd like to install within Cloud Build to have a test pipeline that downloads latest Cloud Composer version and tests against it, but can't install within Cloud Build as it returns `/composer-dev: not found`

This is what I have so far:

```yaml
steps:
- name: google/cloud-sdk:alpine
  id: Clone repo
  entrypoint: git
  args: ['clone', 'https://github.com/GoogleCloudPlatform/composer-local-dev.git']
- name: python:3.10.10-alpine3.17
  id: install pip
  dir: composer-local-dev
  script: pip install --upgrade pip && pip install . --user && mkdir /workspace/me/ && cp -R /builder/home/.local/bin/ /workspace/me/
- name: gcr.io/cloud-builders/gcloud
  id: composer-dev
  script: ls -laR /workspace/me/ && /workspace/me/bin/composer-dev create --from-image-version ${_COMPOSER_IMAGE_VERSION} tester-airflow
substitutions:
  _COMPOSER_IMAGE_VERSION: 'composer-2.1.5-airflow-2.4.3'
```
 which results in the below (edited) log

```
Starting Step #0 - "Clone repo"
Step #0 - "Clone repo": Pulling image: google/cloud-sdk:alpine
Step #0 - "Clone repo": Cloning into 'composer-local-dev'...
Finished Step #0 - "Clone repo"
Starting Step #1 - "install pip"
...
Step #1 - "install pip": Status: Downloaded newer image for python:3.10.10-alpine3.17
Step #1 - "install pip": docker.io/library/python:3.10.10-alpine3.17
...
Step #1 - "install pip": Building wheels for collected packages: composer-dev
Step #1 - "install pip":   Building wheel for composer-dev (pyproject.toml): started
Step #1 - "install pip":   Building wheel for composer-dev (pyproject.toml): finished with status 'done'
Step #1 - "install pip":   Created wheel for composer-dev: filename=composer_dev-0.9.0-py3-none-any.whl size=45159
Step #1 - "install pip":   WARNING: The script composer-dev is installed in '/builder/home/.local/bin' which is not on PATH.
Step #1 - "install pip":   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Step #1 - "install pip": Successfully installed cachetools-4.2.4 certifi-2022.12.7 charset-normalizer-3.0.1 click-8.1.3 composer-dev-0.9.0 docker-6.0.1 google-api-core-1.34.0 google-auth-1.30.2 google-cloud-artifact-registry-1.7.0 google-cloud-orchestration-airflow-1.6.1 googleapis-common-protos-1.58.0 grpc-google-iam-v1-0.12.6 grpcio-1.51.1 grpcio-status-1.48.2 idna-3.4 markdown-it-py-2.1.0 mdurl-0.1.2 packaging-23.0 proto-plus-1.22.2 protobuf-3.20.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 pygments-2.14.0 requests-2.28.2 rich-13.3.1 rich-click-1.4 rsa-4.9 six-1.16.0 urllib3-1.26.14 websocket-client-1.5.1
Step #1 - "install pip": /workspace/me/bin:
Step #1 - "install pip": -rwxr-xr-x    1 root     root           229 Feb 14 11:40 composer-dev
...
Finished Step #1 - "install pip"
Starting Step #2 - "composer-dev"
Step #2 - "composer-dev": /workspace/me/bin:
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  229 Feb 14 11:40 composer-dev
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  225 Feb 14 11:40 markdown-it
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  249 Feb 14 11:40 normalizer
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  220 Feb 14 11:40 pygmentize
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  217 Feb 14 11:40 pyrsa-decrypt
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  217 Feb 14 11:40 pyrsa-encrypt
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  215 Feb 14 11:40 pyrsa-keygen
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  238 Feb 14 11:40 pyrsa-priv2pub
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  211 Feb 14 11:40 pyrsa-sign
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  215 Feb 14 11:40 pyrsa-verify
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  218 Feb 14 11:40 rich-click
Step #2 - "composer-dev": -rwxr-xr-x 1 root root  221 Feb 14 11:40 wsdump
Step #2 - "composer-dev": script: 2: /workspace/me/bin/composer-dev: not found
Finished Step #2 - "composer-dev"
ERROR
ERROR: build step 2 "gcr.io/cloud-builders/gcloud" failed: step exited with non-zero status: 127
```

**Comment by piotrwrotniak** [comment]
Please add the python packages path to PATH as instructed in the output:
```
Step #1 - "install pip":   WARNING: The script composer-dev is installed in '/builder/home/.local/bin' which is not on PATH.
Step #1 - "install pip":   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

**Comment by MarkEdmondson1234** [comment]
Thanks for reply!  The python packages were added to PATH, but are still not recognized by Cloud Build.  It works locally, but perhaps there is something specific for Cloud Build?  Some more edited highlights, stressing the PATH.

I've tried various things, such as `/builder/home/.local/bin/composer-dev`, env vars etc so its only in desperation I write here ;) - any help pointing to an example where its already running on Cloud Build for Cloud Composer 2 testing purposes would also be a solution (and popular I'd imagine)

I can't see how all these things are true:

1. Its installed: `The script composer-dev is installed in '/builder/home/.local/bin'`
2. That location is on PATH: `Step #2 - "composer-dev": /builder/home/.local/bin/:/builder/google-cloud-sdk/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
3. It still can't find `composer-dev` - `Step #2 - "composer-dev": script: 2: composer-dev: not found`


```yaml
steps:
- name: google/cloud-sdk:alpine
  id: Clone repo
  entrypoint: git
  args: ['clone', 'https://github.com/MarkEdmondson1234/composer-local-dev.git']
- name: python:3.10.10-alpine3.17
  id: install pip
  dir: composer-local-dev
  script: ls -la && pip install --upgrade pip && pip install . --user
- name: gcr.io/cloud-builders/gcloud
  id: composer-dev
  script: export PATH=/builder/home/.local/bin/:$PATH && echo $PATH && composer-dev create --from-image-version ${_COMPOSER_IMAGE_VERSION} tester-airflow
substitutions:
  _COMPOSER_IMAGE_VERSION: 'composer-2.1.5-airflow-2.4.3'
```

which results in logs:

```
starting build "8871bbda-f19b-425e-bebe-4a647420793c"

...

BUILD
Starting Step #0 - "Clone repo"
Step #0 - "Clone repo": Pulling image: google/cloud-sdk:alpine
Step #0 - "Clone repo": alpine: Pulling from google/cloud-sdk
...
Step #0 - "Clone repo": Cloning into 'composer-local-dev'...
Finished Step #0 - "Clone repo"
Starting Step #1 - "install pip"
Step #1 - "install pip": Pulling image: python:3.10.10-alpine3.17
...
Step #1 - "install pip":   WARNING: The script composer-dev is installed in '/builder/home/.local/bin' which is not on PATH.
Step #1 - "install pip":   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Step #1 - "install pip": Successfully installed cachetools-4.2.4 certifi-2022.12.7 charset-normalizer-3.0.1 click-8.1.3 composer-dev-0.9.0 docker-6.0.1 google-api-core-1.34.0 google-auth-1.30.2 google-cloud-artifact-registry-1.7.0 google-cloud-orchestration-airflow-1.6.1 googleapis-common-protos-1.58.0 grpc-google-iam-v1-0.12.6 grpcio-1.51.1 grpcio-status-1.48.2 idna-3.4 markdown-it-py-2.1.0 mdurl-0.1.2 packaging-23.0 proto-plus-1.22.2 protobuf-3.20.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 pygments-2.14.0 requests-2.28.2 rich-13.3.1 rich-click-1.4 rsa-4.9 six-1.16.0 urllib3-1.26.14 websocket-client-1.5.1
...
Finished Step #1 - "install pip"
Starting Step #2 - "composer-dev"
Step #2 - "composer-dev": Already have image (with digest): gcr.io/cloud-builders/gcloud
Step #2 - "composer-dev": /builder/home/.local/bin/:/builder/google-cloud-sdk/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Step #2 - "composer-dev": script: 2: composer-dev: not found
Finished Step #2 - "composer-dev"
ERROR
ERROR: build step 2 "gcr.io/cloud-builders/gcloud" failed: step exited with non-zero status: 127
```

**Comment by piotrwrotniak** [comment]
Please try following:
Use python image for the last step as well and follow this guide when installing python packages: https://cloud.google.com/build/docs/building/build-python#configuring_python_builds

My guess is that when you install the pip your way the `/builder/home/.local/bin` path is not shared between steps.

**Comment by MarkEdmondson1234** [comment]
Thanks, made progress!  Using the same Python image for the last step meant it could find the installed folder (can't explain that though as I could see the files via `ls /builder/home/.local/bin` when using the other image.)

However, using `python:3.10.10-alpine3.17` again means I need to install `gcloud` and handle authentication which was the reason to switch in the first place - I'm now looking for an image with `gcloud` installed and authenticated and can have `composer-dev` installed too.

```yaml
steps:
- name: google/cloud-sdk:alpine
  id: Clone repo
  entrypoint: git
  args: ['clone', 'https://github.com/MarkEdmondson1234/composer-local-dev.git']
- name: python:3.10.10-alpine3.17
  id: install pip
  dir: composer-local-dev
  script: ls -la && pip install --upgrade pip && pip install . --user && pip install gcloud --user
- name: python:3.10.10-alpine3.17
  entrypoint: /bin/sh
  id: composer-dev
  args: 
    - -c
    - |-
      export PATH=/builder/home/.local/bin:$$PATH
      echo $$PATH
      composer-dev list-available-versions --include-past-releases --limit 10
substitutions:
  _COMPOSER_IMAGE_VERSION: 'composer-2.1.5-airflow-2.4.3'
```

With logs:

```
Step #0 - "Clone repo": docker.io/google/cloud-sdk:alpine
Step #0 - "Clone repo": Cloning into 'composer-local-dev'...
Finished Step #0 - "Clone repo"
Starting Step #1 - "install pip"
Step #1 - "install pip": Pulling image: python:3.10.10-alpine3.17
...
Step #1 - "install pip": Status: Downloaded newer image for python:3.10.10-alpine3.17
...
Step #1 - "install pip":   WARNING: The script composer-dev is installed in '/builder/home/.local/bin' which is not on PATH.
Step #1 - "install pip":   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Step #1 - "install pip": Successfully installed cachetools-4.2.4 certifi-2022.12.7 charset-normalizer-3.0.1 click-8.1.3 composer-dev-0.9.0 docker-6.0.1 google-api-core-1.34.0 google-auth-1.30.2 google-cloud-artifact-registry-1.7.0 google-cloud-orchestration-airflow-1.6.1 googleapis-common-protos-1.58.0 grpc-google-iam-v1-0.12.6 grpcio-1.51.1 grpcio-status-1.48.2 idna-3.4 markdown-it-py-2.1.0 mdurl-0.1.2 packaging-23.0 proto-plus-1.22.2 protobuf-3.20.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 pygments-2.14.0 requests-2.28.2 rich-13.3.1 rich-click-1.4 rsa-4.9 six-1.16.0 urllib3-1.26.14 websocket-client-1.5.1
...
Finished Step #1 - "install pip"
Starting Step #2 - "composer-dev"
Step #2 - "composer-dev": Already have image: python:3.10.10-alpine3.17
Step #2 - "composer-dev": /builder/home/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Step #2 - "composer-dev": Usage: composer-dev list-available-versions [OPTIONS]
Step #2 - "composer-dev": Try 'composer-dev list-available-versions --help' for help.
Step #2 - "composer-dev": ╭─ Error ──────────────────────────────────────────────────────────────────────╮
Step #2 - "composer-dev": │ Please provide Google Cloud project id (using '-p' / '--project' option).    │
Step #2 - "composer-dev": │ Failed to retrieve project id from gcloud configuration:                     │
Step #2 - "composer-dev": │ Could not validate authentication data: [Errno 2] No such file or directory: │
Step #2 - "composer-dev": │ 'gcloud'.                                                                    │
Step #2 - "composer-dev": │ Please check your internet connection.                                       │
Step #2 - "composer-dev": │ To obtain and export new credentials please run following two commands:      │
Step #2 - "composer-dev": │                                                                              │
Step #2 - "composer-dev": │     $ gcloud auth login                                                      │
Step #2 - "composer-dev": │     $ gcloud auth application-default login                                  │
Step #2 - "composer-dev": │                                                                              │
Step #2 - "composer-dev": │ To obtain new credentials.                                                   │
Step #2 - "composer-dev": │                                                                              │
Step #2 - "composer-dev": │ To print debug messages please add --debug flag.                             │
Step #2 - "composer-dev": ╰──────────────────────────────────────────────────────────────────────────────╯
...
Finished Step #2 - "composer-dev"
ERROR
ERROR: build step 2 "python:3.10.10-alpine3.17" failed: step exited with non-zero status: 2

**Comment by MarkEdmondson1234** [comment]
Ok I'm unblocked :)  Using the same docker image for each step was the solution and what I stumbled across, since I assumed packages installed under a python step would be available for the next.

Working cloudbuild.yaml

```yaml
steps:
- name: google/cloud-sdk:alpine
  id: Clone repo
  entrypoint: git
  args: ['clone', 'https://github.com/MarkEdmondson1234/composer-local-dev.git']
- name: gcr.io/google.com/cloudsdktool/google-cloud-cli:418.0.0
  id: install pip
  dir: composer-local-dev
  script: ls -la && pip install --upgrade pip && pip install . --user
- name: gcr.io/google.com/cloudsdktool/google-cloud-cli:418.0.0
  entrypoint: /bin/sh
  id: composer-dev
  args: 
    - -c
    - |-
      export PATH=/builder/home/.local/bin:$$PATH
      echo $$PATH
      composer-dev list-available-versions --include-past-releases --limit 10
      composer-dev create --from-image-version ${_COMPOSER_IMAGE_VERSION} testairflow
substitutions:
  _COMPOSER_IMAGE_VERSION: 'composer-2.1.5-airflow-2.4.3'
```

Logs:

```
Step #0 - "Clone repo": Cloning into 'composer-local-dev'...
Finished Step #0 - "Clone repo"
Starting Step #1 - "install pip"
Step #1 - "install pip": Pulling image: gcr.io/google.com/cloudsdktool/google-cloud-cli:418.0.0
Step #1 - "install pip": 418.0.0: Pulling from google.com/cloudsdktool/google-cloud-cli
...
Step #1 - "install pip":   WARNING: The script composer-dev is installed in '/builder/home/.local/bin' which is not on PATH.
Step #1 - "install pip":   Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Step #1 - "install pip": Successfully installed cachetools-4.2.4 certifi-2022.12.7 charset-normalizer-3.0.1 click-8.1.3 composer-dev-0.9.0 docker-6.0.1 google-api-core-1.34.0 google-auth-1.30.2 google-cloud-artifact-registry-1.7.0 google-cloud-orchestration-airflow-1.6.1 googleapis-common-protos-1.58.0 grpc-google-iam-v1-0.12.6 grpcio-1.51.1 grpcio-status-1.48.2 idna-3.4 markdown-it-py-2.1.0 mdurl-0.1.2 packaging-23.0 proto-plus-1.22.2 protobuf-3.20.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 pygments-2.14.0 requests-2.28.2 rich-13.3.1 rich-click-1.4 rsa-4.9 six-1.16.0 urllib3-1.26.14 websocket-client-1.5.1
...
Finished Step #1 - "install pip"
Starting Step #2 - "composer-dev"
Step #2 - "composer-dev": Already have image (with digest): gcr.io/google.com/cloudsdktool/google-cloud-cli:418.0.0
Step #2 - "composer-dev": /builder/home/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/google-cloud-sdk/bin/
Step #2 - "composer-dev":                                ╷               
Step #2 - "composer-dev":   Image version                │ Release Date  
Step #2 - "composer-dev": ╶──────────────────────────────┼──────────────╴
Step #2 - "composer-dev":   composer-2.1.5-airflow-2.4.3 │ 08/02/2023    
Step #2 - "composer-dev":   composer-2.1.5-airflow-2.3.4 │ 08/02/2023    
Step #2 - "composer-dev":   composer-2.1.5-airflow-2.2.5 │ 08/02/2023    
Step #2 - "composer-dev":   composer-2.1.4-airflow-2.4.3 │ 01/02/2023    
Step #2 - "composer-dev":   composer-2.1.4-airflow-2.3.4 │ 01/02/2023    
Step #2 - "composer-dev":   composer-2.1.4-airflow-2.2.5 │ 01/02/2023    
Step #2 - "composer-dev":   composer-2.1.3-airflow-2.3.4 │ 16/01/2023    
Step #2 - "composer-dev":   composer-2.1.3-airflow-2.2.5 │ 16/01/2023    
Step #2 - "composer-dev":   composer-2.1.2-airflow-2.3.4 │ 19/12/2022    
Step #2 - "composer-dev":   composer-2.1.2-airflow-2.2.5 │ 19/12/2022    
Step #2 - "composer-dev":                                ╵               
Step #2 - "composer-dev": No dags directory provided, using default dags directory.
Step #2 - "composer-dev": Dags path '/workspace/composer/testairflow/dags' does not exist. It will be 
Step #2 - "composer-dev": created.
Step #2 - "composer-dev": 
Step #2 - "composer-dev": Created environment under composer/testairflow. 
Step #2 - "composer-dev": You can now start it using following command:
Step #2 - "composer-dev": 
Step #2 - "composer-dev": $ composer-dev start testairflow
Step #2 - "composer-dev": 
Step #2 - "composer-dev": You can modify generated files to change your environment settings. 
Step #2 - "composer-dev": Common settings are defined in composer/testairflow/config.json.
Step #2 - "composer-dev": PyPi extra packages are listed in composer/testairflow/requirements.txt.
Step #2 - "composer-dev": Airflow overrides and environment variables are stored in 
Step #2 - "composer-dev": composer/testairflow/variables.env.
Step #2 - "composer-dev": 
Step #2 - "composer-dev": You can put your plugins and data to plugins and data directories 
Step #2 - "composer-dev": available at composer/testairflow.
Step #2 - "composer-dev": DAGs can be updated at /workspace/composer/testairflow/dags path.
Step #2 - "composer-dev": 
Step #2 - "composer-dev": To apply changes done to environment config and PyPI dependencies 
Step #2 - "composer-dev": restart environment using following command:
Step #2 - "composer-dev": 
Step #2 - "composer-dev": $ composer-dev restart testairflow
Step #2 - "composer-dev": 
Finished Step #2 - "composer-dev"
PUSH
DONE
